# Generated by Django 2.2.5 on 2021-04-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('paragraph', models.CharField(max_length=10000)),
                ('outer_img', models.ImageField(upload_to='pics')),
                ('inner_img', models.ImageField(upload_to='pics')),
                ('posted_on', models.DateField()),
            ],
        ),
    ]
