# Generated by Django 2.2.5 on 2021-04-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210423_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='paragraph',
            field=models.TextField(),
        ),
    ]
