# Generated by Django 2.2.5 on 2021-04-24 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210424_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogger_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
