# Generated by Django 2.2.5 on 2021-05-05 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210505_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='short_intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_intro', to='blog.blog')),
            ],
        ),
    ]
