# Generated by Django 2.2.5 on 2021-05-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_short_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='short_intro',
            name='blog',
        ),
        migrations.AddField(
            model_name='short_intro',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
