# Generated by Django 2.2.5 on 2021-05-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210505_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='blog',
            new_name='post',
        ),
    ]
