# Generated by Django 2.2.5 on 2021-05-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_self_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='self_intro',
            name='name',
            field=models.CharField(default='admin', max_length=40),
        ),
    ]
