# Generated by Django 2.2.5 on 2021-05-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210510_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='meme',
        ),
        migrations.AlterField(
            model_name='blog',
            name='paragraph',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
