# Generated by Django 2.2.5 on 2021-05-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_memes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meme',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='paragraph',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, default='title makes the blog look good and meme look bad', max_length=100),
        ),
        migrations.DeleteModel(
            name='memes',
        ),
    ]
