# Generated by Django 2.2.5 on 2021-05-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_blog_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meme_description',
            field=models.TextField(blank=True),
        ),
    ]
