# Generated by Django 2.2.5 on 2021-05-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_blog_meme_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video_description',
            field=models.TextField(blank=True),
        ),
    ]
