# Generated by Django 2.2.5 on 2021-05-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_blog_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='self_intro',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'female'), ('other', 'other')], default='female', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='meme_description',
            field=models.TextField(blank=True, help_text='This will be the description of the meme on the page'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='paragraph',
            field=models.TextField(blank=True, help_text='Dont use this field if you want to put meme or video else it may cause error'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='video_description',
            field=models.TextField(blank=True, help_text='This will be the description of your video on the page'),
        ),
        migrations.AlterField(
            model_name='self_intro',
            name='bio',
            field=models.TextField(help_text='upload atleast seven lines to get proper alignment'),
        ),
        migrations.AlterField(
            model_name='self_intro',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', upload_to='pics'),
        ),
    ]
