# Generated by Django 2.2.5 on 2021-05-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20210513_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='self_intro',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'female'), ('other', 'other')], default='male', max_length=20),
        ),
    ]
