# Generated by Django 2.2.5 on 2021-05-13 18:28

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20210513_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='self_intro',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
