# Generated by Django 2.2.5 on 2021-05-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_self_intro_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='self_intro',
            name='phone',
        ),
    ]
