# Generated by Django 2.2.5 on 2021-05-16 17:23

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_remove_self_intro_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
