# Generated by Django 2.2.5 on 2021-05-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20210516_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, upload_to='vdo'),
        ),
    ]
