# Generated by Django 2.2.5 on 2021-05-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20210516_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='inner_img',
        ),
        migrations.AddField(
            model_name='blog',
            name='inter_para_img',
            field=models.ImageField(blank=True, help_text='This image will be displayed on the middle of the paragraph', upload_to='pics'),
        ),
    ]
