# Generated by Django 2.2.5 on 2021-05-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20210516_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='final_img',
            field=models.ImageField(blank=True, help_text='This image will be displayed on the end of the paragraph', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='final_paragraph',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='first_img',
            field=models.ImageField(blank=True, help_text='This image will be displayed on the start of the paragraph', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='paragraph',
            field=models.TextField(blank=True, help_text='Dont use any paragraph field if you want to put meme or video else it may cause error'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='paragraph2',
            field=models.TextField(blank=True),
        ),
    ]
