# Generated by Django 2.2.5 on 2021-05-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20210517_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subscribers',
            new_name='subscribers_list',
        ),
    ]
