# Generated by Django 2.2.5 on 2021-05-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20210517_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribed_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='subscribers_list',
        ),
    ]
