# Generated by Django 2.2.5 on 2021-05-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20210517_1408'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subscribed_members',
            new_name='subscribers',
        ),
    ]
