# Generated by Django 2.2.5 on 2021-05-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20210517_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subscribers',
            new_name='users',
        ),
    ]
