# Generated by Django 2.2.5 on 2021-05-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_remove_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
