# Generated by Django 2.2.5 on 2021-05-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_auto_20210519_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField(blank=True, help_text='this text will be dispalyed in about our websites tab')),
            ],
        ),
        migrations.CreateModel(
            name='health_care_cordinators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='admin', max_length=40)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'female'), ('other', 'other')], default='male', max_length=20)),
                ('picture', models.ImageField(blank=True, default='default.png', upload_to='pics')),
                ('bio', models.TextField(help_text='upload atleast seven lines to get proper alignment')),
            ],
        ),
        migrations.CreateModel(
            name='tech_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='admin', max_length=40)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'female'), ('other', 'other')], default='male', max_length=20)),
                ('picture', models.ImageField(blank=True, default='default.png', upload_to='pics')),
                ('bio', models.TextField(help_text='upload atleast seven lines to get proper alignment')),
            ],
        ),
    ]
