# Generated by Django 2.2.5 on 2021-05-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_about_site_health_care_cordinators_tech_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='self_intro',
            new_name='cordinators_team_bio',
        ),
        migrations.RenameModel(
            old_name='health_care_cordinators',
            new_name='experts_team_bio',
        ),
    ]
