# Generated by Django 2.2.5 on 2021-05-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20210527_1309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about_site',
            new_name='website_about',
        ),
    ]
