# Generated by Django 2.2.5 on 2021-05-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_auto_20210527_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='supporters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='admin', max_length=40)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'female'), ('other', 'other')], default='male', max_length=20)),
                ('picture', models.ImageField(blank=True, default='default.png', upload_to='pics')),
                ('bio', models.TextField(help_text='upload atleast seven lines to get proper alignment')),
            ],
        ),
    ]
