# Generated by Django 2.2.5 on 2021-05-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_supporters'),
    ]

    operations = [
        migrations.CreateModel(
            name='supporters_non_teaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='admin', max_length=40)),
                ('picture', models.ImageField(blank=True, default='default.png', upload_to='pics')),
            ],
        ),
    ]
