# Generated by Django 2.2.5 on 2021-06-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_supporters_non_teaching'),
    ]

    operations = [
        migrations.AddField(
            model_name='cordinators_team_bio',
            name='qualification_or_designation',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='experts_team_bio',
            name='qualification_or_designation',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='supporters',
            name='qualification_or_designation',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
